@echo off
chcp 65001 > nul
set PYTHONIOENCODING=utf-8
echo ===================================================
echo PRUEBA DE VISION ARTIFICIAL (OPENCV)
echo ===================================================
echo.
echo Tienes 10 segundos para abrir el juego con el mapa grande...
echo Minimiza esta ventana y deja el juego visible!
echo.
echo 10...
timeout /t 1 /nobreak > nul
echo 9...
timeout /t 1 /nobreak > nul
echo 8...
timeout /t 1 /nobreak > nul
echo 7...
timeout /t 1 /nobreak > nul
echo 6...
timeout /t 1 /nobreak > nul
echo 5...
timeout /t 1 /nobreak > nul
echo 4...
timeout /t 1 /nobreak > nul
echo 3...
timeout /t 1 /nobreak > nul
echo 2...
timeout /t 1 /nobreak > nul
echo 1...
timeout /t 1 /nobreak > nul
echo.
echo CAPTURANDO AHORA!
echo.
python src\automation\vision_proximity.py
pause
